version: 2.1
executors:
  node-executor:
    docker:
      - image: node:18
    working_directory: ~/project

jobs:
  test-node:
    executor: node-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

workflows:
  build-and-test:
    jobs:
      - test-node
