version: 2.1

executors:
  node-executor:
    docker:
      - image: node:18
    working_directory: ~/project

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Unit Tests
          command: npm test

  docker_build_and_test:
    docker:
      - image: docker:20.10.24
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            cd Dockerfiles && \
            docker-compose build
      - run:
          name: Run Integration Tests
          command: |
            docker-compose up -d && \
            sleep 10 && \
            docker-compose exec app npm test && \
            docker-compose down

workflows:
  version: 2
  test_and_build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - docker_build_and_test:
          requires:
            - test
