version: 2.1
orbs:
  node: circleci/node@5

executors:
  node-executor:
    docker:
      - image: cimg/node:18 # Imagen actualizada
    working_directory: ~/project

jobs:
  test-node:
    executor: node-executor
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install jest-junit
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./test-results/

  docker-build-and-test:
    executor:
      docker:
        - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker-compose -f docker-compose.yml build
      - run:
          name: Run Tests in Docker
          command: |
            docker-compose -f docker-compose.yml up -d
            sleep 10
            docker exec $(docker ps -qf "name=app") npm test
      - run:
          name: Clean Up Docker
          command: docker-compose down && docker system prune -af
      - store_artifacts:
          path: ./logs/

workflows:
  build-and-test:
    jobs:
      - test-node
      - docker-build-and-test:
          requires:
            - test-node
